name: tetris game CI CD 
on: 
    push: 
        branches: 
            - main 
    pull_request: 
        branches: 
            - main
    workflow_dispatch:
      inputs:
        job_to_run:
          description: "Which job should run?"
          required: true
          type: choice
          options:
            - Testing
            - Docker-builds
            - terraform-builds 
permissions: 
    id-token: write 
    contents: read  
jobs: 
    Testing:
        if: ${{ inputs.job_to_run == 'Testing' }}
        defaults: 
            run: 
                working-directory: ./Tetris-V2
        runs-on: ubuntu-latest 
        steps: 
            - name: Code checkout 
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0       # fetches all the history required for Sonarqube analysis   

            - name: setting up Node js 
              uses: actions/setup-node@v4 
              with: 
                node-version: "18"
                
            
            - name: installing dependencies
              run: npm ci 
            
            - name: SonarQube scan 
              uses: sonarsource/sonarqube-scan-action@v4
              env: 
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            

            - name: Sonar Quality Gate check 
              uses: sonarsource/sonarqube-quality-gate-action@v1
              timeout-minutes: 5 
              env: 
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: OWASP Dependency Check
              uses: dependency-check/Dependency-Check_Action@main
              with:
                project: 'tetris-devsecops'
                path: '.'
                format: 'HTML'
                out: 'reports'
                args: >
                    --enableRetired

            - name: Upload dependency check report 
              uses: actions/upload-artifact@v4 
              with: 
                name: dependency-check-reports
                path: report 


            - name: Trivy fs scan 
              uses: aquasecurity/trivy-action@v0.36.0
              with:
               scan-type: 'fs'
               scan-ref: '.'
               format: 'table'
               severity: 'CRITICAL,HIGH,MEDIUM'
               exit-code: '0'
    
            - name: trivy Fs scan report 
              if: always()
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'json'
                output: 'trivy-fs-report.json'
                severity: 'CRITICAL,HIGH,MEDIUM'
                exit-code: '0'


            - name: Upload Trivy Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: trivy-fs-report
                path: trivy-fs-report.json

    Docker-builds:
        if: ${{ inputs.job_to_run == 'Docker-builds' }}
        runs-on: ubuntu-latest
        needs: Testing 
        defaults: 
            run: 
                working-directory: ./Tetris-V2 
        steps: 
            - name: checkout code 
              uses: actions/checkout@v4

            - name: Setting up nodejs 
              uses: actions/setup-node@v1
              with: 
                node-version: 16  
            - name: Installing dependencies 
              run: npm ci 
            
            - name: Building the docker image 
              run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/tetrisv2:1.0.0 . 

            
            # after building lets go for a trivy image scan 
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/tetrisv2:1.0.0'
                format: 'table'
                exit-code: '0'
                ignore-unfixed: true
                severity: 'CRITICAL,HIGH'
            
            # setting up docker build x : provides more advanced capabilities 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Pushing to dockerHUB 
              run: docker push ${{secrets.DOCKERHUB_USERNAME}}/tetrisv2:1.0.0

    terraform-builds: 
      if: ${{ inputs.job_to_run == 'terraform-builds' }}
      # needs: Docker-builds 
      defaults: 
        run: 
          working-directory: EKS-TF
      runs-on: ubuntu-latest
      steps: 
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS credentials 
            uses: aws-actions/configure-aws-credentials@v4
            with: 
              role-to-assume: arn:aws:iam::815802019107:role/GitHubActionsTerraformRole
              aws-region: ap-south-1

          - name: SetUp terraform 
            uses: hashicorp/setup-terraform@v3 
          
          - name: terraform init 
            run: terraform init 

          - name: Terraform format check 
            run: terraform fmt 
          
          - name: terraform validate 
            run: terraform validate

          - name: plan 
            run: terraform plan 
           
          - name: Applying configurations 
            run: terraform apply -auto-approve 


            

            
    
